[project]
name = 'Decentralized-Manufacturing-Supply-Chain-Visibility'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.component-tracking]
path = 'contracts/component-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.delivery-confirmation]
path = 'contracts/delivery-confirmation.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-verification]
path = 'contracts/entity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-verification]
path = 'contracts/quality-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
